application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: production
  experimental_mode: false

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  multi_port: [9000, 9001, 9002]

logging:
  level: INFO
  format: json
  output: /var/log/experimental.log
  ai_analysis: disabled

database:
  host: cluster.example.com
  port: 5432
  name: devops_experimental
  distributed: true

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  chaos_engineering: enabled

ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

environments:
  production:
    enabled: true
    port: 8080
    hot_reload: false
    debug_mode: false
    mock_apis: false

  development:
    enabled: false
    port: 3000
    hot_reload: true
    debug_mode: true
    mock_apis: true

  testing:
    enabled: false
    port: 9000
    ssl_enabled: true
    ai_mode: true
